---

- vars:
    vm_user_home: /home/{{ vm_user }}
    pyenv_root: '{{ vm_user_home }}/.pyenv'

- name: pyenv source cloned
  tags:
    - pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: {{ pyenv_root }}

- name: pyenv root set
  tags:
    - pyenv
  lineinfile:
    path: '{{ vm_user_home }}/.bash_profile'
    state: present
    regex: ^export PYENV_ROOT={{ pyenv_root }}
    line: 'export PYENV_ROOT={{ pyenv_root }}'
    insertafter: EOF

- name: pyenv PATH set
  tags:
    - pyenv
  lineinfile:
    path: '{{ vm_user_home }}/.bash_profile'
    state: present
    regex: ^export PATH={{ pyenv_root }}/bin
    line: 'export PATH={{ pyenv_root }}/bin:$PATH'
    insertafter: EOF

- name: pyenv initiated
  tags:
    - pyenv
  lineinfile:
    path: '{{ vm_user_home }}/.bash_profile'
    state: present
    regex: ^if command -v pyenv
    line: 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi'
    insertafter: EOF
  
- name: pyenv virtualenv present
  tags:
    - pyenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: '{{ pyenv_root }}/plugins/pyenv-virtualenv'
