---

- name: pyenv depencencies present
  yum:
    name: ['gcc', 'zlib-devel', 'bzip2', 'bzip2-devel', 'readline-devel', 'sqlite', 'sqlite-devel',
    'openssl-devel', 'tk-devel', 'libffi-devel']
    state: present

- name: pyenv root present
  file:
    path: '{{ pyenv_root }}'
    state: directory
    mode: '0777'

- name: pyenv source cloned
  tags:
      - pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: '{{ pyenv_root }}'

- name: pyenv root set
  tags:
    - pyenv
  lineinfile:
    path: '{{ user_home }}/.bash_profile'
    state: present
    regex: ^export PYENV_ROOT={{ pyenv_root }}
    line: 'export PYENV_ROOT={{ pyenv_root }}'
    insertafter: EOF

- name: pyenv PATH set
  tags:
    - pyenv
  lineinfile:
    path: '{{ user_home }}/.bash_profile'
    state: present
    regex: ^export PATH={{ pyenv_root }}/bin
    line: 'export PATH={{ pyenv_root }}/bin:$PATH'
    insertafter: EOF

- name: pyenv initiated
  tags:
    - pyenv
  lineinfile:
    path: '{{ user_home }}/.bash_profile'
    state: present
    backrefs: '{{item.backrefs}}'
    regex: '{{item.regexp}}'
    line: '{{item.line}}'
    insertafter: EOF
  with_items:
    - {backrefs: no, regexp: 'if command -v pyenv', line: 'if command -v pyenv 1>/dev/null 2>&1; then'}
    - {backrefs: no, regexp: '  eval \".*\"', line: '  eval "$(pyenv init -)"'}
    - {backrefs: no, regexp: '  eval \".*\"\nfi', line: 'fi'}

- name: pyenv virtualenv present
  tags:
    - pyenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: '{{ pyenv_root }}/plugins/pyenv-virtualenv'