---

- name: pyenv source cloned
  tags:
    - pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /home/{{vm_user}}/.pyenv

- name: pyenv root set
  tags:
    - pyenv
  lineinfile:
    path: /home/{{vm_user}}/.bash_profile
    state: present
    regex: '^export PYENV_ROOT=/home/{{vm_user}}/.pyenv'
    line: 'export PYENV_ROOT=/home/{{vm_user}}/.pyenv'
    insertafter: EOF

- name: pyenv PATH set
  tags:
    - pyenv
  lineinfile:
    path: /home/{{vm_user}}/.bash_profile
    state: present
    regex: '^export PATH=/home/{{vm_user}}/.pyenv/bin:\\$PATH'
    line: 'export PATH=/home/{{vm_user}}/.pyenv/bin:$PATH'
    insertafter: EOF

# - name: pyenv initiated
#   tags:
#     - pyenv
  
