---

- name: Docker YUM depencies present
  tags:
    - docker
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    state: present

- name: Docker present
  tags:
    - docker
  yum:
    state: present
    name: docker-compose

- name: Docker started
  tags:
    - docker
  service:
    name: docker
    state: started

- name: User in Docker group
  tags:
    - docker
  user:
    name: root
    groups: docker
    append: yes