---
- hosts: local
  become: yes
  vars:
    user_home: '{{ user_home }}'
    pyenv_root: '{{ user_home }}/.pyenv'
  roles:
#    - { role: docker, tags: ['docker'] }
#    - { role: docker-ce, tags: ['docker', 'docker-ce'] }
    - { role: pyenv, tags: ['pyenv'] }
